### ISSUE TITLE
Laravel CMS needs a new name

### ISSUE THREAD

**Issue by bambamboole** [oscer-io/oscer#123]
Laravel is a Trademark which rights belong to Taylor Otwell.
Because of this we need to rename Laravel CMS to something else.

All CMS I know have a name without "CMS" in it.
- Wordpress
- TYPO3
- Drupal
- Wagtail
- Statamic

Maybe this is something we should also follow. 

Requirements:
* It must no registered company or trademark. 
* It must be something with a free domain.  .com/.org/.io would be nice.  
* It must be available as GitHub team name

Topics we could communicate
* Lightweight
* Easy to use
* Modern
* Publishing
* Paper
* Blogging
* ...

Thanks in advance for any suggestions.

**Comment by slashplusweb** [comment]
Here are some of my ideas i originally invented for my own brand. Maybe something that sounds interesting or can be inspiring.

| Name        | Domain available  |
| ------------- |:-------------:| 
| tinyspider |  :white_check_mark: |
| weborigami |  :white_check_mark: |
| webraw |  :white_check_mark: |
| ironpaper |  :white_check_mark: |
| matterpix |  :white_check_mark: |
| linklion |  :white_check_mark: |
| lionink |  :white_check_mark: |
| polarlab |  :white_check_mark: |
| polardroid | :white_check_mark: |
| solarpolar |  :white_check_mark: |
| thinkvolt | :white_check_mark: |
| pixavolt |  :white_check_mark: |
| bezels | :white_check_mark: |
| marginstudio |  :white_check_mark: |
| vooza |  :white_check_mark: |
| polarcore |  :white_check_mark: |
| rivercore |  :white_check_mark: |
| wondervolt |  :white_check_mark: |
| scraft |  :white_check_mark: |
| scriptsoul | :white_check_mark: |
| soulscript |  :white_check_mark: |

**Comment by bambamboole** [comment]
Paperpress
Free .io Domain
Free Github org
(free of charge) trademark search also good: https://www3.wipo.int/branddb/en/showData.jsp?ID=DETM.DE30042820

**Comment by bambamboole** [comment]
Draft CMS
Free: http://draft-cms.org/
Free: Github Org

**Comment by bambamboole** [comment]
Pancil
Free .io Domain, free pancil-cms.org domain
Free Github org
No TM found.

**Comment by bambamboole** [comment]
larpu
{laravel|publishing}
Available as any domain!!!

**Comment by bambamboole** [comment]
oscer
Open source content editor & renderer
:-)
There is an org with this name.

**Comment by bambamboole** [comment]
done!
